name: firebase_auth_web
description: The web implementation of firebase_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
version: 5.4.0

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  firebase_auth_platform_interface: ^6.14.0
  firebase_core: ^2.11.0
  firebase_core_web: ^2.4.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0
  intl: ^0.18.0
  js: ^0.6.3
  meta: ^1.8.0

dev_dependencies:
  firebase_auth: ^4.5.0
  firebase_core_platform_interface: ^4.7.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthWeb
        fileName: firebase_auth_web.dart
